
"Viajes" = [
    {
        "Id": 1,
        "Imagen": 1,
        "Región": "Sur",
        "Provincia": "Río Negro",
        "Ciudad": "Bariloche",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada":	"Aeropuerto Internacional Teniente Luis Candelaria",
        "LugaresAVisitar":	"Centro, Centro Cívico Bariloche, Cerro Campanario, Cerro Catedral, Teleférico Cerro Otto, Parque Nacional Nahuel Huap.",
        "Hotel": "Hotel Bariloche",
        "Precio": 1,	
        
    },
    {
        "Id": 2,
        "Imagen": 2,
        "Región": "Sur",
        "Provincia": "Santa Cruz",
        "Ciudad": "Calafate",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto Internacional Comandante Armando Tola de El Calafate",
        "LugaresAVisitar":	"Centro, Centro de Interpretación Histórica Calafate, Parque Nacional Los Glaciares.",
        "Hotel": "Hotel Calafate",
        "Precio": 1,	
    },
    {
        "Id": 3,
        "Imagen": 3,
        "Región": "Centro",
        "Provincia": "Buenos Aires",
        "Ciudad": "Capital Federal",
        "Salida": "-",
        "Llegada": "Aeropuerto Internacional Ministro Pistarini",
        "LugaresAVisitar":	"Centro, Obelisco, Teatro Colon, Casa Rosada, Plaza de Mayo, Puerto Madero, Puente de la Mujer, Rosedal de Palermo, San Telmo, La Boca.",
        "Hotel": "Hotel Capital Federal",
        "Precio": 1,	
    },
    {
        "Id": 4,
        "Imagen": 4,
        "Región": "Norte",
        "Provincia": "Misiones",
        "Ciudad": "Cataratas de Iguazú",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto Internacional Cataratas del Iguazú",
        "LugaresAVisitar":	"Centro, Triple Frontera, Parque Nacional Iguazú.",
        "Hotel": "Hotel Cataratas de Iguazú",
        "Precio": 1,	
    },
    {
        "Id": 5,
        "Imagen": 5,
        "Región": "Centro",
        "Provincia": "Córdoba",
        "Ciudad": "Córdoba",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto de Córdoba",
        "LugaresAVisitar":	"Centro, Catedral Nuestra Señora de la Asunción de Córdoba, Paseo del Buen Pastor.",
        "Hotel": "Hotel Córdoba",
        "Precio": 1,	
    },
    {
        "Id": 6,
        "Imagen": 6,
        "Región": "Norte",
        "Provincia": "San Salvador de Jujuy",
        "Ciudad": "Jujuy",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto Internacional Gobernador Horacio Guzmán",
        "LugaresAVisitar":	"Centro, Humahuaca, Purmamarca y Salinas Grandes.",
        "Hotel": "Hotel Jujuy",
        "Precio": 1,	
    },
    {
        "Id": 7,
        "Imagen": 7,
        "Región": "Centro",
        "Provincia": "Buenos Aires",
        "Ciudad": "La Plata",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto de La Plata",
        "LugaresAVisitar":	"Centro, Catedral de La Plata, República de los Niños.",
        "Hotel": "Hotel La Plata",
        "Precio": 1,	
    },
    {
        "Id": 8,
        "Imagen": 8,
        "Región": "Centro",
        "Provincia": "Buenos Aires",
        "Ciudad": "Mar del Plata",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto Internacional Ástor Piazzolla",
        "LugaresAVisitar":	"Centro, Catedral de La Plata, República de los Niños.",
        "Hotel": "Hotel Mar del Plata",
        "Precio": 1,	
    },
    {
        "Id": 9,
        "Imagen": 9,
        "Región": "Centro",
        "Provincia": "Mendoza",
        "Ciudad": "Mendoza",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto Internacional El Plumerillo - Mendoza",
        "LugaresAVisitar": "Centro, Bodegas de Mendoza, Cerro de los Siete Colores, Parque Provincial Aconcagua.",
        "Hotel": "Hotel Mendoza",
        "Precio": 1,	
    },
    {
        "Id": 10,
        "Imagen": 10,
        "Región": "Sur",
        "Provincia": "Chubut",
        "Ciudad": "Puerto Madryn",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto El Tehuelche",
        "LugaresAVisitar": "Centro, Playa de Puerto Madryn, Reserva Lobería de Punta Loma.",
        "Hotel": "Hotel Puerto Madryn",
        "Precio": 1,	
    },
    {
        "Id": 11,
        "Imagen": 11,
        "Región": "Centro",
        "Provincia": "Buenos Aires",
        "Ciudad": "Rosario",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto Internacional Rosario Islas Malvinas",
        "LugaresAVisitar": "Centro, Monumento Historico Nacional a la Bandera, Parque Nacional a la Bandera, Parque de la Independencia.",
        "Hotel": "Hotel Rosario",
        "Precio": 1,	
    },
    {
        "Id": 12,
        "Imagen": 12,
        "Región": "Norte",
        "Provincia": "Salta",
        "Ciudad": "Salta",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto Internacional de Salta Martín Miguel de Güemes",
        "LugaresAVisitar": "Centro, Cafayate, Salinas Grandes.",
        "Hotel": "Hotel Salta",
        "Precio": 1,	
    },
    {
        "Id": 13,
        "Imagen": 13,
        "Región": "Centro",
        "Provincia": "Santa Fé",
        "Ciudad": "Santa Fé",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto de Sauce Viejo",
        "LugaresAVisitar": "Centro, Puente Colgante.",
        "Hotel": "Hotel Santa Fé",
        "Precio": 1,	
    },
    {
        "Id": 14,
        "Imagen": 14,
        "Región": "Norte",
        "Provincia": "San Miguel de Tucumán",
        "Ciudad": "Tucumán",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto Internacional Teniente Benjamín Matienzo",
        "LugaresAVisitar": "Centro, Casa Histórica - Museo Nacional de la Independencia, Tafí del Valle.",
        "Hotel": "Hotel Tucumán",
        "Precio": 1,	
    },
    {
        "Id": 15,
        "Imagen": 15,
        "Región": "Sur",
        "Provincia": "Tierra del Fuego",
        "Ciudad": "Ushuaia",
        "Salida": "Aeroparque Jorge Newbery",
        "Llegada": "Aeropuerto Internacional de Ushuaia",
        "LugaresAVisitar": "Centro, Museo Marítimo y del Presidio de Ushuaia, Parque Nacional Tierra del Fuego, Museo y Tren del Fin del Mundo.",
        "Hotel": "Hotel Ushuaia",
        "Precio": 1,	
    },
]